name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE: ${{ vars.REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.ARTIFACT_REPO }}/${{ vars.SERVICE_NAME }}:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: gcloud info

      - name: Docker auth
        run: |-
          gcloud auth configure-docker ${{ vars.REGION }}-docker.pkg.dev --quiet

      - name: Build image
        run: docker build -t ${{ env.IMAGE }} .

      - name: Push image
        run: docker push ${{ env.IMAGE }}

      - name: Deploy
        run: |
          gcloud run deploy ${{ vars.SERVICE_NAME }} \
          --image ${{ env.IMAGE }} \
          --region ${{ vars.REGION }} \
          --service-account=${{ vars.SERVICE_ACCOUNT }} \
          --set-secrets=PERSONA_CREATOR_API_BASE_URL=persona-creator-api-base-url:1
